# Run `pre-commit install --hook-type commit-msg && pre-commit run --all-files`
default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: detect-private-key
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: name-tests-test
      - id: no-commit-to-branch
        args: [--branch, staging, --branch, main, --branch, master]

  # YAML style
  - repo: https://github.com/adrienverge/yamllint
    rev: '*'
    hooks:
      - id: yamllint

  # Markdown style
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: '*'
    hooks:
      - id: markdownlint
        args: [--disable, MD013, MD033, MD041]

  # Spelling / typos
  - repo: https://github.com/codespell-project/codespell
    rev: '*'
    hooks:
      - id: codespell
        args: [--ignore-words-list, "te,thru,ons"]
  # Typos (additional)
  - repo: https://github.com/crate-ci/typos
    rev: '*'
    hooks:
      - id: typos

  # ESLint (JavaScript/TypeScript/Svelte)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: '*'
    hooks:
      - id: eslint
        args: [--fix]
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint@9.18.0
          - typescript@5.0.0
          - eslint-plugin-svelte@3.0.0
          - '@typescript-eslint/parser@8.20.0'
          - '@typescript-eslint/eslint-plugin@8.20.0'
          - eslint-config-prettier@10.1.5
          - svelte
          - globals

  # Prettier (includes prettier‑plugin‑svelte & tailwind class sorter)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: '*'
    hooks:
      - id: prettier
        args: [--write]
        additional_dependencies:
          - prettier-plugin-svelte
          - prettier-plugin-tailwindcss

  # Stylelint for CSS/Tailwind in <style> blocks
  - repo: https://github.com/pre-commit/mirrors-stylelint
    rev: '*'
    hooks:
      - id: stylelint
        args: [--fix]
        additional_dependencies:
          - stylelint
          - stylelint-config-prettier
          - stylelint-config-tailwindcss

  # Local node‑based hooks ---------------------------------
  - repo: local
    hooks:
      # SvelteKit type & a11y checking
      - id: svelte-check
        name: svelte-check
        entry: npx --no-install svelte-check --tsconfig ./tsconfig.json
        language: system
        pass_filenames: false

      # Unit tests with Vitest
      - id: vitest
        name: vitest
        entry: npx --no-install vitest run --coverage
        language: system
        pass_filenames: false
        always_run: true       # run even if only doc files changed

  # Commit‑message linting (separate hook type)
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: npx --no-install commitlint --edit $1
        language: system
        stages: [commit-msg]
