[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
command = "tuigreet -r -g 'Access is restricted to authorized personnel only.' --theme 'border=magenta;text=magenta;prompt=magenta;action=magenta;button=magenta;container=black;input=magenta' --cmd niri-session"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
